# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Nilesh D Kulkarni"
resume_title:                   "Staff Software Engineer"
resume_contact_email:           "nilesh.cric@gmail.com"
resume_contact_telephone:       "315-854-4313"
resume_contact_address:         "5265 Troy Ave, Fremont, CA"
resume_header_contact_info: "nilesh.cric@gmail.com"
resume_header_intro: "<p>Senior Software Developer with solid background in building backend RestFul services, building test automation frameworks and developer productivity tools. Experience in leading and managing a small to medium sized team. An Open source enthusiast. Looking for a challenging role in Software Development or Software Development in Test <p>Open Source Contributions: nemo.js, nemo-view, generator-nemo, webdriverjs-accessibility, grunt-cucumberjs, browsermob-node, webdriver-accessibility</p><p>Technical Reviewer: Mastering Selenium 3.0 WebDriver: Second Edition</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/nikulkarni"
  resume_twitter_url:           "http://twitter.com/nileshdk"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/nileshkulkarni/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://stackoverflow.com/users/503804/nilesh"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
